services:
  - type: web
    name: youtube-rating-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn musicrate.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9