services:
  - type: web
    name: youtube-rating-app
    env: python
    buildCommand: "cd musicrate && pip install -r requirements.txt"
    startCommand: "cd musicrate && gunicorn musicrate.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9